-- MySQL Script generated by MySQL Workbench
-- Thu Jan  5 22:18:04 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`University`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`University` ;

CREATE TABLE IF NOT EXISTS `mydb`.`University` (
  `ID` INT NOT NULL,
  `Location` INT NULL,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Students`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Students` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Students` (
  `ID` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Surname` VARCHAR(45) NULL,
  `Age` INT NULL,
  `Course` INT NULL,
  `University_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Students_University1_idx` (`University_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Students_University1`
    FOREIGN KEY (`University_ID`)
    REFERENCES `mydb`.`University` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Lectors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Lectors` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Lectors` (
  `ID` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Surname` VARCHAR(45) NULL,
  `Age` INT NULL,
  `University_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Lectors_University1_idx` (`University_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Lectors_University1`
    FOREIGN KEY (`University_ID`)
    REFERENCES `mydb`.`University` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Audience`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Audience` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Audience` (
  `ID` INT NOT NULL,
  `Lectors_ID` INT NOT NULL,
  `Students_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `Lectors_ID`, `Students_ID`),
  INDEX `fk_Audience_Lectors_idx` (`Lectors_ID` ASC) VISIBLE,
  INDEX `fk_Audience_Students1_idx` (`Students_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Audience_Lectors`
    FOREIGN KEY (`Lectors_ID`)
    REFERENCES `mydb`.`Lectors` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Audience_Students1`
    FOREIGN KEY (`Students_ID`)
    REFERENCES `mydb`.`Students` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`timestamps`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`timestamps` ;

CREATE TABLE IF NOT EXISTS `mydb`.`timestamps` (
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL);


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP);


-- -----------------------------------------------------
-- Table `mydb`.`timestamps_1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`timestamps_1` ;

CREATE TABLE IF NOT EXISTS `mydb`.`timestamps_1` (
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL);


-- -----------------------------------------------------
-- Table `mydb`.`user_1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user_1` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user_1` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP);


-- -----------------------------------------------------
-- Table `mydb`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`category` ;

CREATE TABLE IF NOT EXISTS `mydb`.`category` (
  `category_id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`category_id`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
